---
- name: Converge
  hosts: all
  tasks:
    - name: "Include ansible-role-zookeeper"
      include_role:
        name: "ansible-role-zookeeper"
      vars:
        zookeeper_user: root
        zookeeper_group: root
        zookeeper_secure_client_port: null
        zookeeper_extra_properties: |
          zookeeper.client.secure=false
