---
dependency:
  name: galaxy
driver:
  name: podman
lint: |
  set -e
  yamllint .
  ansible-lint .
platforms:
  - name: zookeeper-centos7
    image: "geerlingguy/docker-centos7-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
     - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
  - name: zookeeper-centos8
    image: "geerlingguy/docker-centos8-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
     - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
  - name: zookeeper-debian9
    image: "geerlingguy/docker-debian9-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
     - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
#  - name: zookeeper-debian10
#    image: "geerlingguy/docker-debian10-ansible:latest"
#    command: ${MOLECULE_DOCKER_COMMAND:-""}
#    volumes:
#     - /sys/fs/cgroup:/sys/fs/cgroup:ro
#    privileged: true
provisioner:
  name: ansible
  playbooks:
    prepare: ../resources/playbooks/prepare.yml
verifier:
  name: testinfra
