---
- name: Prepare
  hosts: all
  tasks:
    - name: Install openjdk
      package:
        name:
          - openjdk-8-jdk
        update_cache: true
      when:
        - "ansible_distribution|lower == 'debian'"
        - "ansible_distribution_major_version|int == 9"

    - name: Install openjdk
      package:
        name:
          - openjdk-11-jdk
        update_cache: true
      when:
        - "ansible_distribution|lower == 'debian'"
        - "ansible_distribution_major_version|int == 10"

    - name: Install openjdk
      package:
        name:
          - java-11-openjdk
      when:
        - "ansible_distribution|lower == 'centos'"
